// apps/web/src/lib/components/application/AppBar.svelte
<script>
	import { AppBar } from '@skeletonlabs/skeleton';
	import Icon from '@iconify/svelte';
	import { appVersion } from '$lib/utils/appInfo';
	import BotLogo from '$lib/assets/logos/BotLogo.svelte';

	let expanded = false;
</script>

<AppBar
	class="border-surface-500/10 dark:border-surface-50/10 sticky"
	background="transparent backdrop-blur-sm"
	padding="p-0"
	border="border-b-[1px]"
	regionRowMain="py-3 max-w-7xl px-2 sm:px-6 lg:px-8 mx-auto w-full"
	gridColumns="grid-cols-1"
	slotDefault="flex w-full relative"
>
	<!-- Nav left -->

	<button
		class="btn btn-sm absolute inset-y-0 left-0 flex items-center p-2 sm:hidden"
		on:click={() => (expanded = !expanded)}
	>
		<Icon
			icon={expanded ? 'heroicons:x-mark' : 'heroicons:bars-3'}
			class="text-surface-900-50-token"
			height="auto"
		/>
	</button>

	<!-- Nav Main -->

	<div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
		<a href="/" class="btn btn-sm flex items-center space-x-3 px-2 py-1">
			<div class="mb-1 ml-1 h-7">
				<BotLogo width={22} />
			</div>
			<strong class="text-surface-900-50-token hidden select-none text-xl font-light sm:block"
				>KideAppBot</strong
			>
		</a>
	</div>

	<!-- Nav Right -->

	<div
		class="absolute inset-y-0 right-0 flex items-center space-x-2 pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0"
	>
		<!-- Version number -->

		<span class="text-surface-800-100-token font-mono text-sm opacity-50">{appVersion}</span>

		<!-- GitHub link -->

		<a
			href="https://github.com/AleksiVirkkala/KideAppBot"
			aria-label="KideAppBot GitHub repository"
			class="btn btn-icon btn-icon-sm"
		>
			<Icon icon="mdi:github" height="unset" class="text-surface-900-50-token h-7" />
		</a>
	</div>
</AppBar>

// packages/ui/src/application/AppBar.tsx
'use client';

import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline';
import { BotLogo, GitHubLogo } from '../assets/Logos';
import { Disclosure } from '@headlessui/react';
import Link from 'next/link';
import { ElementType, FC, Fragment } from 'react';
import { twMerge } from 'tailwind-merge';

export interface NavigationOption {
  label: string;
  href: string;
  isActive: boolean;
}

const AppLogo = () => (
  <Link
    href="/"
    className="flex items-center space-x-3 rounded-md px-2 focus:outline-none focus:ring-2 focus:ring-zinc-900/10"
  >
    <BotLogo className="mb-1 block h-7 w-auto fill-indigo-500" />
    <BotLogo.Text className="hidden sm:block" />
  </Link>
);
const GitHubLink = () => (
  <a
    href="https://github.com/AleksiVirkkala/KideAppBot"
    className="rounded-full focus:outline-none focus:ring-2 focus:ring-zinc-900/10"
  >
    <GitHubLogo className="block h-7 fill-zinc-700 hover:fill-zinc-950" />
  </a>
);

const NavLeft: FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">{children}</div>
);
const NavMain: FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
    {children}
  </div>
);
const NavRight: FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="absolute inset-y-0 right-0 flex items-center space-x-4 pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
    {children}
  </div>
);

const VersionNumber: FC<{ children: React.ReactNode }> = ({ children }) => (
  <span className="font-w font-mono text-sm text-zinc-700 opacity-50">{children}</span>
);

const DesktopNavigation: FC<{ options: NavigationOption[]; className?: string }> = ({
  options,
  className
}) => (
  <div className={twMerge('ml-6', className)}>
    <div className="flex space-x-4">
      {options.map(option => (
        <Link
          key={option.label}
          href={option.href}
          className={twMerge(
            option.isActive
              ? 'bg-zinc-500/10'
              : 'text-zinc-700 hover:bg-zinc-500/5 hover:text-zinc-900',
            'rounded-md px-3 py-2 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-zinc-900/10'
          )}
          aria-current={option.isActive ? 'page' : undefined}
        >
          {option.label}
        </Link>
      ))}
    </div>
  </div>
);

const MobileNavigation: FC<{ options: NavigationOption[]; className?: string }> = ({
  options,
  className
}) => (
  <Disclosure.Panel className={className}>
    <div className="space-y-1 px-2 pb-3 pt-2">
      {options.map(option => (
        <Disclosure.Button
          key={option.label}
          as={Link}
          href={option.href}
          className={twMerge(
            option.isActive
              ? 'bg-zinc-500/10'
              : 'text-zinc-700 hover:bg-zinc-500/5 hover:text-zinc-900',
            'block rounded-md px-3 py-2 text-base font-medium focus:outline-none focus:ring-2 focus:ring-zinc-900/10'
          )}
          aria-current={option.isActive ? 'page' : undefined}
        >
          {option.label}
        </Disclosure.Button>
      ))}
    </div>
  </Disclosure.Panel>
);
const MobileMenuButton: FC<{ isOpen: boolean }> = ({ isOpen }) => (
  <Disclosure.Button className="inline-flex items-center justify-center rounded-md p-2 text-zinc-400 hover:bg-zinc-500/5 hover:text-zinc-900 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-zinc-500/10">
    <span className="sr-only">Open main menu</span>
    {isOpen ? (
      <XMarkIcon className="block h-6 w-6" aria-hidden="true" />
    ) : (
      <Bars3Icon className="block h-6 w-6" aria-hidden="true" />
    )}
  </Disclosure.Button>
);

interface AppBarProps {
  navigationOptions: NavigationOption[];
  versionNumber?: string;
  as?: ElementType;
  className?: string;
  logo?: React.ReactNode;
}

export const AppBar = ({
  navigationOptions,
  versionNumber,
  as: Wrapper = 'nav',
  className,
  logo: Logo = <AppLogo />
}: AppBarProps) => {
  return (
    <Wrapper className={twMerge('sticky inset-x-0 top-0 z-50 backdrop-blur-sm', className)}>
      <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <Disclosure as={Fragment}>
          {({ open }) => (
            <>
              <div className="relative flex h-16 items-center justify-between">
                <NavLeft>
                  <MobileMenuButton isOpen={open} />
                </NavLeft>
                <NavMain>
                  {Logo}
                  <DesktopNavigation options={navigationOptions} className="hidden sm:block" />
                </NavMain>
                <NavRight>
                  <VersionNumber>{versionNumber}</VersionNumber>
                  <GitHubLink />
                </NavRight>
              </div>
              <MobileNavigation options={navigationOptions} className="sm:hidden" />
            </>
          )}
        </Disclosure>
      </div>
      {/* Separator line at AppBar bottom */}
      <div className="absolute inset-x-0 top-full h-px bg-zinc-900/10" />
    </Wrapper>
  );
};
