// apps/web/src/lib/components/application/AppBar/AppBarShell.svelte
<script>
	import { twMerge } from '$lib/actions';
	import { slide } from 'svelte/transition';

	let className = '';
	export { className as class };
	export let expanded = false;
	export let appBarContent = '';
	export let expandContent = '';
	export let background = 'transparent';
</script>

<header use:twMerge={className} class="sticky inset-x-0 top-0 z-50">
	<!-- Static content -->

	<div use:twMerge={[appBarContent, background]}>
		<div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
			<slot />
		</div>
	</div>

	<!-- Border will be visible even when menu is closed -->
	<div
		use:twMerge={[expandContent, background]}
		class="border-surface-500/10 dark:border-surface-50/10 absolute inset-x-0 border-b-[1px]"
	>
		<!-- Expand content -->
		{#if expanded}
			<div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8" transition:slide>
				<slot name="expandContent" />
			</div>
		{/if}
	</div>
</header>

// packages/ui/src/application/AppBar/AppBarShell.tsx
import * as Collapsible from '@radix-ui/react-collapsible';
import { Dispatch, SetStateAction, useState } from 'react';
import { twMerge } from 'tailwind-merge';
import { ExpandTransition } from '../../helpers/Motion/ExpandTransition';

export type AppBarContent = React.FC<{
  isExpanded: boolean;
  setIsExpanded: Dispatch<SetStateAction<boolean>>;
}>;

interface AppBarShellProps {
  children: AppBarContent;
  collapsibleContent?: AppBarContent;
  className?: string;
  as?: React.ElementType;
}

/**
 * AppBar Shell
 *
 * This component has 2 primary content areas:
 * - The bar itself
 * - Content that can be expanded below the bar
 */
export const AppBarShell: React.FC<AppBarShellProps> = ({
  children: Children,
  as: Wrapper = 'header',
  className,
  collapsibleContent: Content
}) => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <Collapsible.Root asChild open={isExpanded} onOpenChange={setIsExpanded}>
      <Wrapper className="sticky inset-x-0 top-0 z-50">
        {/* Static blocking content */}
        <div className={className}>
          <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            <Children isExpanded={isExpanded} setIsExpanded={setIsExpanded} />
          </div>
        </div>
        {/* Border will be visible even when menu is closed */}
        <div className={twMerge('absolute inset-x-0 border-b-[1px]', className)}>
          {/* Dynamically shown "floating" content */}
          {Content && (
            <ExpandTransition
              expanded={isExpanded}
              className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8"
            >
              <Collapsible.Content asChild>
                <Content isExpanded={isExpanded} setIsExpanded={setIsExpanded} />
              </Collapsible.Content>
            </ExpandTransition>
          )}
        </div>
      </Wrapper>
    </Collapsible.Root>
  );
};
