// apps/web/src/lib/components/application/AppBar/AppBar.svelte
<script context="module" lang="ts">
	export interface NavigationOption {
		label: string;
		href: string;
		isActive: boolean;
	}
</script>

<script lang="ts">
	import AppBarShell from './AppBarShell.svelte';
	import Icon from '@iconify/svelte';
	import { appVersion } from '$lib/utils/appInfo';
	import BotLogo from '$lib/assets/logos/BotLogo.svelte';

	export let expanded = false;
	export let navOptions: NavigationOption[] = [];
</script>

<AppBarShell {expanded} background="backdrop-blur-sm">
	<div class="relative flex items-center justify-between py-3">
		<!-- Header left -->

		<button
			class="btn btn-sm absolute left-0 flex items-center p-2 sm:hidden"
			on:click={() => (expanded = !expanded)}
		>
			<Icon
				icon={expanded ? 'heroicons:x-mark' : 'heroicons:bars-3'}
				class="text-surface-900-50-token"
				height="auto"
			/>
		</button>

		<!-- Header Main -->

		<div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
			<!-- Bot Logo -->

			<a href="/" class="btn btn-sm flex items-center space-x-3 px-2 py-1">
				<div class="mb-1 ml-1 h-7">
					<BotLogo width={22} />
				</div>
				<strong class="text-surface-900-50-token hidden select-none text-xl font-light sm:block"
					>KideAppBot</strong
				>
			</a>

			<!-- Desktop Navigation -->

			<nav class="ml-6 flex items-center space-x-4 max-sm:hidden">
				{#each navOptions as { href, isActive, label }}
					<a
						{href}
						class="btn btn-sm h-8 {isActive ? 'variant-glass-surface' : 'bg-surface-hover-token'}"
						>{label}</a
					>
				{/each}
			</nav>
		</div>

		<!-- Header Right -->

		<div
			class="absolute inset-y-0 right-0 flex items-center space-x-2 pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0"
		>
			<!-- Version number -->

			<span class="text-surface-800-100-token font-mono text-sm opacity-50">{appVersion}</span>

			<!-- GitHub link -->

			<a
				href="https://github.com/AleksiVirkkala/KideAppBot"
				aria-label="KideAppBot GitHub repository"
				class="btn btn-icon btn-icon-sm"
			>
				<Icon icon="mdi:github" height="unset" class="text-surface-900-50-token h-7" />
			</a>
		</div>
	</div>

	<svelte:fragment slot="expandContent">
		<nav class="space-y-1 px-2 pb-3 pt-2 sm:hidden">
			{#each navOptions as { href, isActive, label }}
				<a
					{href}
					class="btn btn-sm block h-8 text-left {isActive
						? 'variant-glass-surface'
						: 'bg-surface-hover-token'}">{label}</a
				>
			{/each}
		</nav>
	</svelte:fragment>
</AppBarShell>

// packages/ui/src/application/AppBar/AppBar.tsx
'use client';

import { BotLogo, GitHubLogo } from '../../assets/Logos';
import Link from 'next/link';
import { ElementType, FC } from 'react';
import { twMerge } from 'tailwind-merge';
import { MenuButton } from './MenuButton';
import { AppBarContent, AppBarShell } from './AppBarShell';

export interface NavigationOption {
  label: string;
  href: string;
  isActive: boolean;
}

const AppLogoLink = () => (
  <Link
    href="/"
    className="flex items-center space-x-3 rounded-md px-2 focus:outline-none focus:ring-2 focus:ring-zinc-900/10"
  >
    <BotLogo className="mb-1 block h-7 w-auto fill-indigo-500" />
    <BotLogo.Text className="hidden sm:block" />
  </Link>
);
const GitHubLink = () => (
  <a
    href="https://github.com/AleksiVirkkala/KideAppBot"
    className="rounded-full focus:outline-none focus:ring-2 focus:ring-zinc-900/10"
  >
    <GitHubLogo className="block h-7 fill-zinc-700 hover:fill-zinc-950" />
  </a>
);

const NavLeft: FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">{children}</div>
);
const NavMain: FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
    {children}
  </div>
);
const NavRight: FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="absolute inset-y-0 right-0 flex items-center space-x-4 pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
    {children}
  </div>
);
const VersionNumber: FC<{ children: React.ReactNode }> = ({ children }) => (
  <span className="font-w font-mono text-sm text-zinc-700 opacity-50">{children}</span>
);

const NavItem: FC<{ option: NavigationOption; className?: string }> = ({ option, className }) => (
  <Link
    href={option.href}
    className={twMerge(
      option.isActive ? 'bg-zinc-500/10' : 'text-zinc-700 hover:bg-zinc-500/5 hover:text-zinc-900',
      'rounded-md px-3 py-2 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-zinc-900/10',
      className
    )}
    aria-current={option.isActive ? 'page' : undefined}
  >
    {option.label}
  </Link>
);

const DesktopNavigation: FC<{ options: NavigationOption[]; className?: string }> = ({
  options,
  className
}) => (
  <div className={twMerge('ml-6', className)}>
    <nav className="flex space-x-4">
      {options.map(option => (
        <NavItem key={option.label} option={option} />
      ))}
    </nav>
  </div>
);
const MobileNavigation: FC<{ options: NavigationOption[]; className?: string }> = ({
  options,
  className
}) => (
  <div className={className}>
    <nav className="space-y-1 px-2 pb-3 pt-2">
      {options.map(option => (
        <NavItem key={option.label} option={option} className="block" />
      ))}
    </nav>
  </div>
);

interface AppBarProps {
  navigationOptions: NavigationOption[];
  versionNumber?: string;
  as?: ElementType;
  className?: string;
  logo?: React.ReactNode;
}

export const AppBar = ({
  navigationOptions,
  versionNumber,
  logo = <AppLogoLink />,
  as,
  className
}: AppBarProps) => {
  const collapsibleContent: AppBarContent = () => (
    <MobileNavigation options={navigationOptions} className="sm:hidden" />
  );
  return (
    <AppBarShell
      as={as}
      collapsibleContent={collapsibleContent}
      className={twMerge('backdrop-blur-sm', className)}
    >
      {({ isExpanded }) => (
        <div className="relative flex h-16 items-center justify-between">
          <NavLeft>
            <MenuButton isOpen={isExpanded} />
          </NavLeft>
          <NavMain>
            {logo}
            <DesktopNavigation options={navigationOptions} className="hidden sm:block" />
          </NavMain>
          <NavRight>
            <VersionNumber>{versionNumber}</VersionNumber>
            <GitHubLink />
          </NavRight>
        </div>
      )}
    </AppBarShell>
  );
};

AppBar.NavItem = NavItem;
